# Generated by Django 3.0.3 on 2020-07-23 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=1.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(blank=True, default=111, null=True)),
                ('bill', models.FloatField(default=1.0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('Grams', 'Grams'), ('Dozen', 'Dozen'), ('Liters', 'Liters'), ('Piece', 'Piece'), ('Plate', 'Plate'), ('Other', 'Other')], default='KG', max_length=20)),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Add', 'Add'), ('Remove', 'Remove')], default='Add', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bk_app.StockItem')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bk_app.Deal')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bk_app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.FloatField(default=1.0)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('Grams', 'Grams'), ('Dozen', 'Dozen'), ('Liters', 'Liters'), ('Piece', 'Piece'), ('Plate', 'Plate'), ('Other', 'Other')], default='KG', max_length=20)),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bk_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('units', models.CharField(choices=[('KG', 'KG'), ('Grams', 'Grams'), ('Dozen', 'Dozen'), ('Liters', 'Liters'), ('Piece', 'Piece'), ('Plate', 'Plate'), ('Other', 'Other')], default='KG', max_length=20)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bk_app.Deal')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bk_app.MenuItem')),
            ],
        ),
    ]
