# Generated by Django 3.0.3 on 2020-07-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_app', '0002_ordermenuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='ordermenuitem',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
