# Generated by Django 3.0.3 on 2020-07-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_app', '0003_auto_20200724_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
