# Generated by Django 3.0.3 on 2020-07-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_app', '0004_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charges',
            field=models.FloatField(default=1.0),
        ),
    ]
