# Generated by Django 3.0.3 on 2020-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_app', '0005_order_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_take_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Dine In', 'Dine In'), ('Takeaway', 'Takeaway')], default='Dine In', max_length=20),
        ),
    ]
