# Generated by Django 3.0.3 on 2020-07-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bk_app', '0006_auto_20200724_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_take_name',
            new_name='order_taker_name',
        ),
    ]
