# Generated by Django 3.0.3 on 2020-07-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_app', '0008_auto_20200724_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='no',
            field=models.PositiveIntegerField(blank=True, default=111, null=True),
        ),
    ]
